### ISSUE TITLE
Portable Binary (Pyinstaller)

### ISSUE THREAD

**Issue by Emen0s** [NUKIB/maldump#3]
Hello !

I'm very interested at this project !
I would like to make an executable using Pyinstaller in order to forensically extract quarantines files on computers without Python installed.
Do you think it is possible ?

Thank you so much !

**Comment by JohnyBembel** [comment]
Hello!

We are happy to see your interest in our project. We were migrating some work in progress, and the project is now finally updated, so please first check the new updates. There is now an issue template for feature suggestions so I will close this issue. Please create a new one following the template.

The standalone binary is a great idea, which we have in mind, too. We definitely think it is possible; however, during some brief research, we found it a rather difficult task. But with some effort, it is definitely doable.

If you join our [discord](https://discord.com/invite/VYZADbrm), we can discuss the possibilities and help you with the creation of this feature. We appreciate your willingness to contribute and are looking forward to cooperating.

Have a good day!
